include:
  - project: 'dropLoop/ci-templates'
    ref: master
    file: 'node/core.yml'
  - project: 'dropLoop/ci-templates'
    ref: master
    file: 'node/pika-publish.yml'
  - project: 'dropLoop/ci-templates'
    ref: master
    file: 'node/meta.yml'
  - project: 'dropLoop/ci-templates'
    ref: master
    file: 'node/dependencies.yml'

stages:
  - meta
  - test
  - build
  - publish
